### ISSUE TITLE
Option to remove site from List API while still being functional

### ISSUE THREAD

**Issue by Andre601** [botblock/data#50]
There should be a setting within the JSON file to indicate that a site is functional (`defunct: 0`) but may not support BotBlock and its API methods to post or get bot data.

There are currently two lists that match this case:
- Top.gg: Intentionally blocks requests from the BotBlock API IPs as the owner is banned I guess
- Discordextremelist.xyz: Uses IP-based rate limiting without API key, resulting in a higher amount of rate limits for BotBlock itself.

These are the sites I'm aware of that either have problems with the BotBlock API or intentionally deny support for it.
A setting to then f.e. add a notice to the Site info may be useful. Or perhaps remove it completely from the API in such cases.

I hope you get what I want to say.

**Comment by MattIPv4** [comment]
I'm not sure it would make sense for us to actually remove a list that has an API from BotBlock's API integration. If folks are having trouble with those lists through BotBlock, the best bet would be for them to stop including them. We list the API information for those lists, and make use of it, because those lists have a published API.

I'd also call out that for both of the lists you mention, the issue was with the old deployment model for BotBlock where all traffic originated from a single source IP. BotBlock is now deployed globally with Cloudflare Workers, so I doubt either of these is an active issue anymore.

If we do need to add a note on the site about lists, the existing `content` field on lists should be used for this -- it should render as a notice on the list page.

**Comment by Andre601** [comment]
Fair enough.
